version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    expose:
    - 8090
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
      - redisdb
    links:
      - mongodb
      - redisdb
  mongodb:
    image: mongo
    volumes:  
    - ./data:/data/db
    expose:
    - 12707
    ports:
      - "12707:12707"

  redisdb:
    image: redis
    expose:
    - 6379
    ports:
      - "6378:6379"
    volumes:
    - ./data/redis:/data